// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/files": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all files with uploader details (admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminFileListResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/generate-token": {
            "post": {
                "description": "Admin-only: generate JWT token for a user (login as user)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Generate JWT for user",
                "parameters": [
                    {
                        "description": "Payload with username",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminGenerateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT token for user",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminGenerateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Missing username",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/share": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows admins to share files with users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Admin share file",
                "parameters": [
                    {
                        "description": "File share details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves overall usage statistics (admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get usage stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AdminStatsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows admins to upload files on behalf of users",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Admin upload file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Uploader (username)",
                        "name": "uploader",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users": {
            "get": {
                "description": "Returns all user details (admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates user and returns JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "User login payload",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful (returns username, email, token, role)",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid login payload",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "401": {
                        "description": "Login failed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Registers a new user with username, email, and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration payload",
                        "name": "registerRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Registration failed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/delete": {
            "post": {
                "description": "Deletes a file owned by the user. Only the uploader can delete. Deduplication respected.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Delete a file",
                "parameters": [
                    {
                        "description": "Delete file payload (fileId, username)",
                        "name": "deleteRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found or not owned",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/delete-filename": {
            "post": {
                "description": "Deletes a file for a user by filename. Supports deletion of duplicate files uploaded as copies.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Delete a file by filename",
                "parameters": [
                    {
                        "description": "Delete file by filename payload (filename, username)",
                        "name": "deleteRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteFileByFilenameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found or not owned",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/owned": {
            "get": {
                "description": "Returns files where the user has 'owner' permission",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "List files owned by user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username to list owned files for",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of owned files",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserFile"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing username",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/path/download": {
            "get": {
                "description": "Serves a file from storage by its path",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Get file by path",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path relative to storage/",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File served successfully",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/path/view": {
            "get": {
                "description": "Serves a file from storage by its path for browser viewing",
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "file"
                ],
                "summary": "View file by path",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path relative to storage/",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File served for viewing",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/public-share": {
            "post": {
                "description": "Generates a public link for a file, accessible to anyone with the link. Accepts filename and username in request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Share file publicly by filename",
                "parameters": [
                    {
                        "description": "Public share payload (filename, username)",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PublicShareByFilenameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Public share link generated",
                        "schema": {
                            "$ref": "#/definitions/dto.PublicShareResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found or not owned",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/rename": {
            "post": {
                "description": "Renames a file owned by the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Rename a file",
                "parameters": [
                    {
                        "description": "Rename file payload. Required: filename, newName, username.",
                        "name": "renameRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FileRenameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File renamed successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "404": {
                        "description": "File not found or not owned",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/search": {
            "get": {
                "description": "Search and filter files by filename, MIME type, size, date, tags, uploader",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file-search"
                ],
                "summary": "Search files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filename to search",
                        "name": "filename",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "MIME type filter",
                        "name": "mimeType",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum file size",
                        "name": "minSize",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum file size",
                        "name": "maxSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start upload date",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End upload date",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Uploader's name",
                        "name": "uploader",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.FileMeta"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/file/share": {
            "post": {
                "description": "Shares a file with a recipient, granting permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file-share"
                ],
                "summary": "Share a file with another user",
                "parameters": [
                    {
                        "description": "File share payload",
                        "name": "shareRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File shared successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/file/share/revoke": {
            "post": {
                "description": "Revokes sharing of a file for a recipient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file-share"
                ],
                "summary": "Revoke sharing of a file",
                "parameters": [
                    {
                        "description": "Revoke share payload",
                        "name": "revokeRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File share revoked",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/file/shared-with-me": {
            "get": {
                "description": "Returns files where shared_with = username and permission != 'owner'",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "List files shared with user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username to list files shared with",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of files shared with user",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserFile"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing username",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/shared/list": {
            "get": {
                "description": "Lists files shared with or by the specified username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file-share"
                ],
                "summary": "List files shared with/by a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username to list shared files for",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of shared files",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.UserFile"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.FileShareResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/file/storage-quota": {
            "get": {
                "description": "Returns the storage quota used by the user in MB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Get user storage quota used",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username to check storage quota for",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Storage quota used",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing username",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/storage/analytics": {
            "get": {
                "description": "Returns analytics: user count, file count, deduplication savings, etc.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "File storage analytics",
                "responses": {
                    "200": {
                        "description": "Analytics data",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/file/upload": {
            "post": {
                "description": "Uploads a file, validates MIME type, and deduplicates using SHA-256 hash. Returns reference if duplicate.\nUpload multiple files. Each file is processed and returns status for each.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file",
                    "file"
                ],
                "summary": "Upload one or more files",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Files to upload (multiple allowed)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Uploader (username)",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Files processed",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request or MIME type mismatch",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/file/upload-meta": {
            "post": {
                "description": "Accepts multiple files and metadata, saves all to database. Supports optional folder path.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Upload one or more files with metadata",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Files to upload (multiple allowed)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Uploader (username)",
                        "name": "uploader",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder path (optional, defaults to /home)",
                        "name": "path",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Files and metadata uploaded",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AdminFile": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "downloadCount": {
                    "type": "integer"
                },
                "fileSize": {
                    "type": "number"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mimeType": {
                    "type": "string"
                },
                "uploader": {
                    "type": "string"
                }
            }
        },
        "dto.AdminFileListResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AdminFile"
                    }
                }
            }
        },
        "dto.AdminGenerateTokenRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.AdminGenerateTokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.AdminShareRequest": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string"
                },
                "permission": {
                    "description": "e.g., \"viewer\", \"editor\"",
                    "type": "string"
                },
                "shareWith": {
                    "description": "Username to share with",
                    "type": "string"
                }
            }
        },
        "dto.AdminStatsResponse": {
            "type": "object",
            "properties": {
                "avgFilesPerUser": {
                    "type": "number"
                },
                "avgStoragePerUser": {
                    "type": "number"
                },
                "deduplicationRatio": {
                    "type": "number"
                },
                "spaceSaved": {
                    "type": "number"
                },
                "totalDownloads": {
                    "type": "integer"
                },
                "totalFiles": {
                    "type": "integer"
                },
                "totalLogicalStorage": {
                    "type": "number"
                },
                "totalPhysicalFiles": {
                    "type": "integer"
                },
                "totalStorageUsed": {
                    "type": "number"
                },
                "totalUsers": {
                    "type": "integer"
                }
            }
        },
        "dto.DeleteFileByFilenameRequest": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteFileRequest": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.FileMeta": {
            "type": "object",
            "properties": {
                "fileSize": {
                    "type": "number"
                },
                "filename": {
                    "description": "The following fields are computed by handlers",
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "referenceCount": {
                    "type": "integer"
                },
                "referenceID": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "uploadDate": {
                    "type": "string"
                },
                "uploader": {
                    "description": "Uploader is provided by user (username)",
                    "type": "string"
                }
            }
        },
        "dto.FileRenameRequest": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "newName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.FileShareRequest": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "permission": {
                    "description": "e.g., \"read\", \"write\"",
                    "type": "string"
                },
                "recipient": {
                    "type": "string"
                }
            }
        },
        "dto.FileShareResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.PublicShareByFilenameRequest": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.PublicShareResponse": {
            "type": "object",
            "properties": {
                "publicUrl": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserFile": {
            "type": "object",
            "properties": {
                "fileId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "permission": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "utils.APIError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "An error occurred"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "utils.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
